version: '3.7'
services:
  jupyter:
    container_name: lspace-jupyter-almond
    image: lspace/jupyter-almond
    ports:
      - '8888:8888'
    volumes:
      - ./examples:/home/jovyan/examples
      # - ~/work:/home/jovyan/work
      - ~/.m2:/home/jovyan/.m2

