language: scala
scala:
  - 2.11.12
  - 2.12.8
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - node_modules
services:
  - cassandra
  - elasticsearch
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - npm install jsdom
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION test site/makeMicrosite
after_success:
  - "bash <(curl -s https://codecov.io/bash) -r $TRAVIS_REPO_SLUG -t $CODECOV_TOKEN"
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: false
  fqdn: docs.l-space.eu
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    scala: 2.12.8
  local-dir: site/target/jekyll
  target-branch: gh-pages
