version: '3'
services:
  metabase:
    container_name: lspace-metabase
    image: "metabase/metabase:latest"
    restart: always
    ports:
      - '3000:3000'
    networks:
      - l-space-network

networks:
  l-space-network:
    external: true
